// Copy this file to config.js for local development.
// In production, config.js is generated by GitHub Actions.

window.API_BASE = "https://YOUR_API_ID.execute-api.ap-northeast-1.amazonaws.com/dev";