version = 0.1

[default.global.parameters]
stack_name = "snake-game-stack"
region     = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"

[default.build.parameters]
cached   = true
parallel = true

[default.deploy.parameters]
confirm_changeset         = false
no_fail_on_empty_changeset = true
resolve_s3                = true
